load("ecoreg.RData")
L <- load("bestmodels_gamm4.RData")

library(gamm4)
library(tidyr)
library(dplyr)
source("mmd_utils.R")

bb <- best_models[["mmamm_log"]]
head(residuals(bb$mer))

## plain
plotfun(bb)
plotfun(bb,xvar="NPP_log")
plotfun(bb,xvar="NPP_log",ylim=NULL)

##
plotfun(bb,backtrans=TRUE,ylim=NULL)
plotfun(bb,backtrans=TRUE,log="xy",ylim=NULL)
plotfun(bb,xvar="Feat_log",backtrans=TRUE,log="xy",ylim=NULL)

## STOPPED HERE
## test remef
ecoreg$rem1 <- drop(remef_allran(best_models[["mmamm_log"]],
                                 data=ecoreg,
                                 set_other="median",
                                 fixed_keep=c("(Intercept)","NPP_log")))
plotfun(bb,respvar="rem1",ylim=c(-1,0.5))+
    theme(legend.position="none")+
    geom_smooth(method="lm",aes(group=1,y=rem1))
plotfun(bb,respvar="rem1",ylim=c(-1,0.5),auxvar=NULL)+
    theme(legend.position="none")+
    geom_smooth(method="lm",aes(group=1,y=rem1))

plotfun(bb)+theme(legend.position="none")
plotfun(bb,auxvar=NULL,grpvar="biome")+theme(legend.position="none")
## by hand
ggplot(ecoreg,aes(NPP_log,rem1,colour=biome))+geom_point()+
    geom_smooth(method="lm",aes(group=1))

## partial resids look OK: but what is the correct regression
## line to plot?  it doesn't seem to be what's generated by predict() ...
## is it just (overall intercept + overall slope) ?
##
## experiment with a simpler example from remef()??

dd <- data.frame(x1=rnorm(100))
dd$x2 <- -0.5*x1+rnorm(100)
dd$y <-


###
rr <- remef_allran(best_models[["mmamm_log"]],data=ecoreg,
                   fixed_keep=NA,return_components=TRUE)
pred2 <- with(rr,pp_ran+pp_fixed)
pred1 <- predict(best_models[["mmamm_log"]]) ## doesn't include smooth term
par(mfrow=c(1,2))
plot(ecoreg$NPP_log,pred1-pred2)
plot(ecoreg$NPP_log,rr$rem)
dd <- data.frame(ecoreg,rr)

       
