load("ecoreg.RData")
L <- load("bestmodels_gamm4.RData")
L <- load("allfits_brms.RData")

library(gamm4)
library(tidyr)
library(dplyr)
library(ggplot2); theme_set(theme_bw())
source("mmd_utils.R")

bb <- best_models[["mmamm_log"]]
head(residuals(bb$mer))
bbr <- allfits_brms[["mmamm_log"]]


## plain
no_legend <- theme(legend.position="none")
plotfun(bb,backtrans=TRUE,log="xy",xvar="Feat_log")
plotfun(bb,backtrans=TRUE,xvar="Feat_log")
plotfun(bb,xvar="Feat_log",backtrans=TRUE,log="xy")+ no_legend
## brms prediction
plotfun(bbr,backtrans=TRUE,log="xy",ylim=log(c(8,250)))+ no_legend
## all looks reasonable

## STOPPED HERE
## test remef
ecoreg$rem1 <- drop(remef_allran(best_models[["mmamm_log"]],
                                 data=ecoreg,
                                 ## set_other="median",
                                 set_other="zero",
                                 keep_intercept=TRUE,
                                 ##fixed_keep=c("(Intercept)","NPP_log")
                                 fixed_keep=c("NPP_log")
                                 ))

## raw/simple
rem2 <- residuals(bb$mer)+cc[1]+cc[2]*ecoreg$NPP_log
plot(rem1~NPP_log,data=ecoreg)
plot(rem2~NPP_log,data=ecoreg)
cc <- coef(bb$gam)[c("(Intercept)","NPP_log")]
abline(a=cc[1],b=cc[2])
## looks OK ?

## remef_allran
plotfun(bb,respvar="rem1",ylim=c(-1,0.8))+
    theme(legend.position="none")+
    geom_smooth(method="lm",aes(group=1,y=rem1),
                formula=y~x-1)
## why have regression/predicted lines disappeared now?
## x,y set to zero??


## something about intercepts: centering/ 0 values?

plotfun(bb,respvar="rem1",ylim=c(-1,0.8),auxvar=NULL,
        adjust_othervar="mean")+
    theme(legend.position="none")+
    geom_smooth(method="lm",aes(group=1,y=rem1))

plotfun(bb,respvar="rem1",ylim=c(-1,0.8))+
    theme(legend.position="none")+
    geom_smooth(method="lm",aes(group=1,y=rem1))
## doesn't match exactly, but close

plotfun(bb)+theme(legend.position="none")
## ????
plotfun(bb,auxvar=NULL,grpvar="biome")+theme(legend.position="none")
## by hand
ggplot(ecoreg,aes(NPP_log,rem1,colour=biome))+geom_point()+
    geom_smooth(method="lm",aes(group=1))

## partial resids look OK: but what is the correct regression
## line to plot?  it doesn't seem to be what's generated by predict() ...
## is it just (overall intercept + overall slope) ?
##
## experiment with a simpler example from remef()??

dd <- data.frame(x1=rnorm(100))
dd$x2 <- -0.5*x1+rnorm(100)
dd$y <-


###
rr <- remef_allran(best_models[["mmamm_log"]],data=ecoreg,
                   fixed_keep=NA,return_components=TRUE)
pred2 <- with(rr,pp_ran+pp_fixed)
pred1 <- predict(best_models[["mmamm_log"]]) ## doesn't include smooth term
par(mfrow=c(1,2))
plot(ecoreg$NPP_log,pred1-pred2)
plot(ecoreg$NPP_log,rr$rem)
dd <- data.frame(ecoreg,rr)

       
